# Imagen base
FROM python:3.8-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos del proyecto al directorio /app en el contenedor
COPY generar_numeros.py /app/
COPY requirements.txt /app/

# Instalar las dependencias (si el requirements.txt no está vacío)
RUN pip install --no-cache-dir -r requirements.txt

# Comando para ejecutar al iniciar el contenedor
CMD ["python", "./generar_numeros.py"]
